### PR TITLE
Fix handling of symbols in serialization

### LINKED ISSUE #36: Packing Dict{Symbol,Any} corrupts data
Reproducer:
```julia
julia> bad = Dict{Symbol,Any}(:wake_after_sleep_onset => 0, :wake_after_sleep_onset_percentage => 1)
Dict{Symbol,Any} with 2 entries:
  :wake_after_sleep_onset            => 0
  :wake_after_sleep_onset_percentage => 1

julia> io = IOBuffer();

julia> pack(io, bad)

julia> seekstart(io);

julia> unpack(io, Dict{Symbol,Any})
Dict{Symbol,Any} with 2 entries:
  :wake_after_sleep_onset => 0x00
  :wake_after_sleep       => 0x5f
```
The keys are truncated and the values are wrong. Also note that the value assigned to the key `:wake_after_sleep` is the code point for an underscore, which would be the continuation of the key name were it completely consumed.

The problem seems to be specific to packing `Symbol`s, as packing as `String` and unpacking as `Symbol` works fine:
```julia
julia> ok = Dict{String,Any}("wake_after_sleep_onset" => 0, "wake_after_sleep_onset_percentage" => 1)
Dict{String,Any} with 2 entries:
  "wake_after_sleep_onset"            => 0
  "wake_after_sleep_onset_percentage" => 1

julia> io = IOBuffer();

julia> pack(io, ok)

julia> seekstart(io);

julia> unpack(io, Dict{Symbol,Any})
Dict{Symbol,Any} with 2 entries:
  :wake_after_sleep_onset            => 0x00
  :wake_after_sleep_onset_percentage => 0x01
```

### PR DESCRIPTION
**Pull request by ararslan**
Fixes #36

### CODE REVIEW

File: test/runtests.jl [hunk 1]
```diff
@@ -44,10 +44,13 @@ end
 
 # StringType
 
-@test can_round_trip(join(rand(Char, 9)), String)
-@test can_round_trip(join(rand(Char, typemax(UInt8) - 1)), String)
-@test can_round_trip(join(rand(Char, typemax(UInt8) + 1)), String)
-@test can_round_trip(join(rand(Char, typemax(UInt16) + 1)), String)
+for T in [String, Symbol], value in [join(rand(Char, 9)),
```
Comment (ararslan) [inline test/runtests.jl]: Actually this is a bad test for `Symbol`s because they're more restrictive than `String`s in terms of the data they can contain. Will fix.
